const storage={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}},remove(k){try{localStorage.removeItem(k)}catch{}}};
let saved=[];try{saved=JSON.parse(storage.get("sunday-shortlist-v2")||"[]")}catch{}
const state={search:"",borough:"all",cost:"all",setting:"all",mode:"all",selected:new Set(Array.isArray(saved)?saved:[])};
const categoriesEl=document.getElementById("categories"),resultCountEl=document.getElementById("resultCount"),emptyStateEl=document.getElementById("emptyState"),shortlistBar=document.getElementById("shortlistBar"),shortlistCount=document.getElementById("shortlistCount"),toast=document.getElementById("toast");
const escapeHTML=v=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
function cardHTML(e,color){const selected=state.selected.has(e.id);const modeTags=e.modes.slice(0,2).map(m=>`<span class="tag mode-tag">${escapeHTML(modeLabels[m])}</span>`).join("");return `<article class="card" data-id="${escapeHTML(e.id)}" style="--cat-color:${color}"><div class="card-top"><div class="time">${escapeHTML(e.time)}</div><button class="shortlist-btn" type="button" data-shortlist="${escapeHTML(e.id)}" aria-pressed="${selected}"><span class="icon" aria-hidden="true">${selected?"✓":"+"}</span><span>${selected?"Selected":"Shortlist"}</span></button></div><h3>${escapeHTML(e.title)}</h3><p class="place">${escapeHTML(e.place)}</p><p class="description">${escapeHTML(e.description)}</p><div class="tags">${modeTags}${e.tags.map(t=>`<span class="tag">${escapeHTML(t)}</span>`).join("")}</div><div class="card-footer"><span class="details-line">${escapeHTML(e.area)} · ${escapeHTML(e.costLabel)} · ${escapeHTML(e.settingLabel)}</span><a class="source-link" href="${escapeHTML(e.url)}" target="_blank" rel="noopener noreferrer" aria-label="Open details for ${escapeHTML(e.title)}">Details <span aria-hidden="true">↗</span></a></div></article>`}
function render(){const grouped=Object.keys(categoryMeta).map(category=>({category,events:events.filter(e=>e.category===category).sort((a,b)=>a.start-b.start||a.title.localeCompare(b.title))}));categoriesEl.innerHTML=grouped.map(g=>{const meta=categoryMeta[g.category];return `<section class="category" data-category="${escapeHTML(g.category)}" style="--cat-color:${meta.color}"><div class="category-heading"><span class="category-mark" aria-hidden="true"></span><h2>${escapeHTML(g.category)}</h2><span class="category-count"></span></div><p class="category-note">${escapeHTML(meta.note)}</p><div class="grid">${g.events.map(e=>cardHTML(e,meta.color)).join("")}</div></section>`}).join("");document.querySelectorAll("[data-shortlist]").forEach(b=>b.addEventListener("click",()=>toggleShortlist(b.dataset.shortlist)));applyFilters();updateShortlistBar()}
function matches(e){const q=state.search.trim().toLowerCase(),hay=[e.title,e.place,e.area,e.description,e.category,...e.tags,...e.modes.map(m=>modeLabels[m])].join(" ").toLowerCase();return(!q||hay.includes(q))&&(state.borough==="all"||e.borough===state.borough)&&(state.cost==="all"||e.cost===state.cost)&&(state.setting==="all"||e.setting===state.setting)&&(state.mode==="all"||e.modes.includes(state.mode))}
function applyFilters(){let total=0;document.querySelectorAll(".category").forEach(section=>{let visible=0;section.querySelectorAll(".card").forEach(card=>{const e=events.find(x=>x.id===card.dataset.id),show=matches(e);card.hidden=!show;if(show)visible++});section.hidden=visible===0;section.querySelector(".category-count").textContent=`${visible} option${visible===1?"":"s"}`;total+=visible});resultCountEl.textContent=`${total} of ${events.length} options shown`;emptyStateEl.classList.toggle("show",total===0)}
function toggleShortlist(id){state.selected.has(id)?state.selected.delete(id):state.selected.add(id);storage.set("sunday-shortlist-v2",JSON.stringify([...state.selected]));const b=document.querySelector(`[data-shortlist="${CSS.escape(id)}"]`),on=state.selected.has(id);b.setAttribute("aria-pressed",String(on));b.querySelector(".icon").textContent=on?"✓":"+";b.querySelector("span:last-child").textContent=on?"Selected":"Shortlist";updateShortlistBar()}
function updateShortlistBar(){const n=state.selected.size;shortlistCount.textContent=`${n} option${n===1?"":"s"} selected`;shortlistBar.classList.toggle("show",n>0)}
function shortlistText(){const chosen=events.filter(e=>state.selected.has(e.id)).sort((a,b)=>a.start-b.start);const lines=chosen.map(e=>`• ${e.time} — ${e.title}\n  ${e.place}\n  ${e.url}`);return `Sunday, July 26 — NYC options\n\n${lines.join("\n\n")}\n\nFull comparison: ${location.href}`}
function showToast(msg){toast.textContent=msg;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),1800)}
async function copyText(text,message){try{await navigator.clipboard.writeText(text);showToast(message)}catch{window.prompt("Copy:",text)}}
async function shareShortlist(){const text=shortlistText();if(navigator.share){try{await navigator.share({title:"Sunday in NYC · July 26",text,url:location.href});return}catch(e){if(e?.name==="AbortError")return}}copyText(text,"Shortlist copied")}
["search","borough","cost","setting","mode"].forEach(id=>document.getElementById(id).addEventListener(id==="search"?"input":"change",ev=>{state[id]=ev.target.value;applyFilters()}));
document.getElementById("resetFilters").addEventListener("click",()=>{Object.assign(state,{search:"",borough:"all",cost:"all",setting:"all",mode:"all"});["search","borough","cost","setting","mode"].forEach(id=>document.getElementById(id).value=id==="search"?"":"all");applyFilters()});
document.getElementById("clearShortlist").addEventListener("click",()=>{state.selected.clear();storage.remove("sunday-shortlist-v2");document.querySelectorAll("[data-shortlist]").forEach(b=>{b.setAttribute("aria-pressed","false");b.querySelector(".icon").textContent="+";b.querySelector("span:last-child").textContent="Shortlist"});updateShortlistBar()});
document.getElementById("shareShortlist").addEventListener("click",shareShortlist);document.getElementById("copyPageLink").addEventListener("click",()=>copyText(location.href,"Page link copied"));render();
